# Generated by Django 4.2.9 on 2026-02-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_budget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='masters.companyprofile'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='masters.companyprofile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('company', 'account', 'month')},
        ),
    ]
