# Generated by Django 4.2.9 on 2026-02-25 11:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Voucher',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('has_gst', models.BooleanField(default=False)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gst_type', models.CharField(blank=True, choices=[('intra', 'Intra-State (CGST+SGST)'), ('inter', 'Inter-State (IGST)')], max_length=10)),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.account')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.journalvoucher')),
            ],
            options={
                'ordering': ['line_order', 'pk'],
            },
        ),
    ]
