# Generated by Django 4.2.9 on 2026-02-26 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_journalvoucher_deleted_at_journalvoucher_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed (Pending Posting)'), ('posted', 'Posted')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored'), ('review', 'Reviewed'), ('post', 'Posted')], max_length=20)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='transactions.journalvoucher')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
