# Generated by Django 4.2.9 on 2026-02-26 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_budget'),
        ('transactions', '0003_journalvoucher_posted_by_journalvoucher_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('narration', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='changes',
        ),
        migrations.CreateModel(
            name='RecurringVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.account')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.recurringvoucher')),
            ],
        ),
    ]
