# Generated by Django 4.2.9 on 2026-02-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_budget_unique_together_account_company_and_more'),
        ('transactions', '0004_recurringvoucher_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='masters.companyprofile'),
        ),
        migrations.AddField(
            model_name='recurringvoucher',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='masters.companyprofile'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='voucher_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='journalvoucher',
            unique_together={('company', 'voucher_number')},
        ),
    ]
